In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

Import the Elviz Data for all 88 samples

In [2]:
from elviz_pca import import_elviz_data


elviz_data = import_elviz_data()

print(elviz_data.abundance.describe())

# are there any null values? 
elviz_data[elviz_data.abundance.isnull()]


#elviz_data = pd.read_csv("./results/reduced_data--genus_only.csv", 
#                        dtype={'abundance':'float'})

# TODO: convert NaN abundances to zero. 
# argument: na_values=None,
# na_values : str, list-like or dict, default None
#    Additional strings to recognize as NA/NaN. If dict passed, specific
#    per-column NA values



count    5.352900e+04
mean     1.643969e-03
std      2.331600e-02
min      2.424267e-07
25%      4.668598e-06
50%      1.749988e-05
75%      9.606543e-05
max      7.984020e-01
Name: abundance, dtype: float64


Empty DataFrame
Columns: [ID, rep, week, oxy, Genus, Length, abundance, project]
Index: []

In [3]:
elviz_data.head()

ID  rep  week   oxy          Genus   Length  abundance  project
0  106_HOW12    4    12  High  Methylobacter  4325001   0.701923  1056226
1   76_LOW10    4    10   Low  Methylobacter  6062067   0.701577  1056166
2   94_HOW11    4    11  High  Methylobacter  5268714   0.698849  1056202
3   82_HOW10    4    10  High  Methylobacter  5488758   0.693746  1056178
4    40_LOW7    4     7   Low  Methylobacter  6012817   0.668513  1056094

In [4]:
# Need to have rows = Genus.  
# samples as columns
# In a way it doesn't matter but it will be easier to plt 
# if we 
#elviz_data_pivoted = elviz_data.pivot(index='Genus', 
#                                      columns='ID', values='abundance')

from elviz_pca import pivot_for_pca

elviz_data_pivoted = pivot_for_pca(elviz_data)

In [5]:
print(elviz_data_pivoted.shape)
elviz_data_pivoted.head()

(977, 88)


ID              100_LOW12  103_HOW12  104_HOW12  105_HOW12  106_HOW12  \
Genus                                                                   
Abiotrophia       0.00000   0.000000   0.000000   0.000000    0.00000   
Acaricomes        0.00000   0.000000   0.000000   0.000000    0.00000   
Acetivibrio       0.00001   0.000000   0.000006   0.000000    0.00000   
Acetobacter       0.00000   0.000005   0.000008   0.000005    0.00003   
Acetobacterium    0.00000   0.000000   0.000000   0.000000    0.00000   

ID              109_LOW13   10_HOW4  110_LOW13     111_LOW13     112_LOW13  \
Genus                                                                        
Abiotrophia      0.000000  0.000000   0.000000  0.000000e+00  0.000000e+00   
Acaricomes       0.000000  0.000000   0.000000  0.000000e+00  0.000000e+00   
Acetivibrio      0.000697  0.000000   0.000253  2.546842e-07  1.397941e-05   
Acetobacter      0.000000  0.000180   0.000201  3.110095e-06  1.188612e-06   
Acetobacterium   0.000000  0.000017   0.000000  4.266709e-07  8.211922e-07   

ID                ...     88_LOW11    8_HOW4  91_HOW11  92_HOW11  93_HOW11  \
Genus             ...                                                        
Abiotrophia       ...     0.000000  0.000000  0.000000  0.000000  0.000000   
Acaricomes        ...     0.000000  0.000000  0.000000  0.000000  0.000000   
Acetivibrio       ...     0.000016  0.000011  0.000003  0.000000  0.000003   
Acetobacter       ...     0.000006  0.000022  0.000007  0.000027  0.000000   
Acetobacterium    ...     0.000000  0.000131  0.000000  0.000000  0.000000   

ID              94_HOW11  97_LOW12  98_LOW12  99_LOW12    9_HOW4  
Genus                                                             
Abiotrophia     0.000000  0.000000  0.000000         0  0.000000  
Acaricomes      0.000000  0.000000  0.000000         0  0.000000  
Acetivibrio     0.000000  0.000002  0.000766         0  0.000000  
Acetobacter     0.000012  0.000006  0.000000         0  0.000083  
Acetobacterium  0.000000  0.000000  0.000000         0  0.000050  

[5 rows x 88 columns]

In [6]:
# Reduce to the most abundant values per sample. 
# Need to drop rows that are below some abundance rowsum. 
from elviz_pca import most_abundant_genera_for_pca

pca_input = most_abundant_genera_for_pca(data=elviz_data_pivoted, top_percent=20)
print(pca_input.shape)
pca_input.head(10)


195
(195, 88)


/Users/janet/elvizAnalysis/elviz_pca.py:40: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  data.sort(columns='row_sum', ascending=False, inplace=True)


ID                100_LOW12  103_HOW12  104_HOW12  105_HOW12  106_HOW12  \
Genus                                                                     
Methylobacter      0.616827   0.225911   0.282648   0.073473   0.701923   
other              0.158067   0.125687   0.093873   0.197769   0.104544   
Methylotenera      0.098789   0.371810   0.028309   0.005347   0.013885   
Methylophilus      0.001554   0.131634   0.445430   0.583474   0.060682   
Methylosarcina     0.006326   0.002396   0.003158   0.000244   0.000454   
Acidovorax         0.009083   0.037599   0.026508   0.035342   0.051723   
Methylomonas       0.012749   0.003361   0.005143   0.001265   0.002982   
Flavobacterium     0.006316   0.017845   0.060173   0.000132   0.000733   
Methylomicrobium   0.008090   0.002830   0.003504   0.004169   0.003965   
Methylovulum       0.003910   0.003447   0.004030   0.007360   0.006497   

ID                109_LOW13   10_HOW4  110_LOW13  111_LOW13  112_LOW13  \
Genus                                                                    
Methylobacter      0.524244  0.103972   0.587177   0.701402   0.593887   
other              0.199694  0.251298   0.191630   0.132675   0.152174   
Methylotenera      0.110765  0.310491   0.002683   0.030411   0.113760   
Methylophilus      0.003104  0.001683   0.003582   0.001463   0.001866   
Methylosarcina     0.010087  0.037925   0.019623   0.008330   0.007219   
Acidovorax         0.015568  0.096500   0.003379   0.004976   0.014307   
Methylomonas       0.020395  0.012791   0.025598   0.018596   0.013413   
Flavobacterium     0.000864  0.012461   0.001763   0.001071   0.004239   
Methylomicrobium   0.020332  0.008001   0.019619   0.006928   0.009433   
Methylovulum       0.010238  0.012969   0.020533   0.005652   0.004567   

ID                  ...     88_LOW11    8_HOW4  91_HOW11  92_HOW11  93_HOW11  \
Genus               ...                                                        
Methylobacter       ...     0.521862  0.084614  0.564363  0.389002  0.597334   
other               ...     0.207534  0.177164  0.160769  0.179035  0.160787   
Methylotenera       ...     0.061106  0.236161  0.013968  0.120259  0.015401   
Methylophilus       ...     0.019801  0.001568  0.004315  0.000694  0.048923   
Methylosarcina      ...     0.042230  0.270019  0.005764  0.005339  0.001724   
Acidovorax          ...     0.015059  0.028095  0.120190  0.097539  0.055727   
Methylomonas        ...     0.016203  0.023263  0.009030  0.009074  0.003661   
Flavobacterium      ...     0.010867  0.030877  0.031021  0.029484  0.000887   
Methylomicrobium    ...     0.008630  0.023409  0.006181  0.007539  0.004055   
Methylovulum        ...     0.004270  0.007130  0.003263  0.007118  0.005692   

ID                94_HOW11  97_LOW12  98_LOW12  99_LOW12    9_HOW4  
Genus                                                               
Methylobacter     0.698849  0.496885  0.544018  0.672948  0.075084  
other             0.090202  0.235220  0.214388  0.146305  0.289090  
Methylotenera     0.031089  0.079913  0.001764  0.029392  0.298211  
Methylophilus     0.003213  0.003772  0.004186  0.003504  0.000939  
Methylosarcina    0.004016  0.009713  0.018936  0.008394  0.031484  
Acidovorax        0.049188  0.027526  0.014359  0.006433  0.037677  
Methylomonas      0.008243  0.019743  0.030577  0.017156  0.017286  
Flavobacterium    0.003224  0.009506  0.005938  0.000874  0.040365  
Methylomicrobium  0.007445  0.018061  0.024848  0.005937  0.008271  
Methylovulum      0.007820  0.009471  0.018284  0.005384  0.009263  

[10 rows x 88 columns]

In [7]:
pca_input

ID                     100_LOW12  103_HOW12  104_HOW12  105_HOW12  106_HOW12  \
Genus                                                                          
Methylobacter       6.168272e-01   0.225911   0.282648   0.073473   0.701923   
other               1.580673e-01   0.125687   0.093873   0.197769   0.104544   
Methylotenera       9.878874e-02   0.371810   0.028309   0.005347   0.013885   
Methylophilus       1.554081e-03   0.131634   0.445430   0.583474   0.060682   
Methylosarcina      6.325981e-03   0.002396   0.003158   0.000244   0.000454   
Acidovorax          9.082583e-03   0.037599   0.026508   0.035342   0.051723   
Methylomonas        1.274855e-02   0.003361   0.005143   0.001265   0.002982   
Flavobacterium      6.315685e-03   0.017845   0.060173   0.000132   0.000733   
Methylomicrobium    8.090268e-03   0.002830   0.003504   0.004169   0.003965   
Methylovulum        3.910306e-03   0.003447   0.004030   0.007360   0.006497   
Pseudomonas         2.344259e-03   0.003324   0.002167   0.004370   0.012510   
Methyloglobulus     3.137332e-03   0.001383   0.001417   0.000292   0.000521   
Bacteriovorax       1.870154e-06   0.000273   0.000445   0.000000   0.000001   
Comamonas           1.843215e-03   0.001404   0.001697   0.012979   0.001732   
Burkholderia        1.761515e-03   0.000883   0.000910   0.001843   0.000965   
Polaromonas         1.111798e-03   0.003658   0.000724   0.001571   0.000796   
Methylocaldum       1.135566e-03   0.000476   0.000317   0.000055   0.000387   
Curvibacter         4.957353e-03   0.002132   0.000439   0.002090   0.001844   
Dechloromonas       6.055259e-04   0.000293   0.000272   0.000587   0.001812   
Variovorax          9.307242e-04   0.001651   0.000479   0.003264   0.001576   
Janthinobacterium   8.715895e-04   0.000596   0.001470   0.002711   0.000739   
Rheinheimera        1.444787e-04   0.000026   0.000007   0.000200   0.000018   
Chitinimonas        2.617622e-03   0.000185   0.000302   0.001860   0.000472   
Nitrosomonas        1.391052e-03   0.000523   0.000387   0.000081   0.000036   
Hylemonella         1.445468e-04   0.005247   0.000329   0.000463   0.000342   
Streptomyces        2.248674e-04   0.000609   0.000372   0.000235   0.001199   
Azospirillum        2.906947e-03   0.000194   0.000206   0.000141   0.000066   
Vibrio              1.963154e-03   0.000530   0.000637   0.000204   0.000071   
Thauera             6.984313e-04   0.000150   0.000202   0.000802   0.000104   
Desulfobacter       1.241559e-04   0.000720   0.001555   0.000007   0.000041   
...                          ...        ...        ...        ...        ...   
Pandoraea           1.886739e-05   0.000057   0.000153   0.000119   0.000068   
Frankia             5.226798e-06   0.000002   0.000177   0.000078   0.000015   
Pseudoxanthomonas   7.976270e-05   0.000046   0.000042   0.000113   0.000027   
Sphingobium         4.993611e-05   0.000052   0.000058   0.000135   0.000040   
Arthrobacter        3.633778e-04   0.000009   0.000000   0.000052   0.000013   
Geodermatophilus    4.043512e-06   0.000005   0.000002   0.000107   0.000012   
Thermomonospora     6.385506e-07   0.000047   0.000288   0.000000   0.000523   
Xenorhabdus         1.588070e-06   0.000074   0.000006   0.000017   0.000061   
Dickeya             1.476520e-04   0.000036   0.000031   0.000056   0.000015   
Desulfurivibrio     1.279095e-04   0.000088   0.000043   0.000023   0.000002   
Hahella             1.202566e-04   0.000013   0.000012   0.000040   0.000033   
Sporocytophaga      2.356886e-05   0.000000   0.000139   0.000007   0.000005   
Dyadobacter         6.231554e-05   0.000006   0.000149   0.000013   0.000002   
Kitasatospora       1.843274e-04   0.000188   0.000003   0.000055   0.000010   
Pontibacter         2.346508e-05   0.000010   0.000172   0.000007   0.000003   
Marinobacterium     1.231744e-04   0.000085   0.000057   0.000079   0.000036   
Thioflavicoccus     2.186730e-04   0.000032   0.000057   0.000002   0.000007   


In [8]:
pca = PCA()
pca.fit(pca_input)

PCA(copy=True, n_components=None, whiten=False)

In [9]:
print(pca.explained_variance_ratio_) 

[  8.14526041e-01   8.39541119e-02   4.29947019e-02   3.45014012e-02
   1.92589065e-02   2.44914631e-03   1.13077215e-03   4.20096980e-04
   1.57308428e-04   1.46541038e-04   1.08608417e-04   6.72805011e-05
   4.43631442e-05   3.51219189e-05   3.41417229e-05   2.50860295e-05
   2.08820559e-05   2.02039077e-05   1.71144286e-05   1.08585490e-05
   9.29791774e-06   7.75127889e-06   7.25480175e-06   6.46051462e-06
   5.68950271e-06   5.01088848e-06   4.83054576e-06   3.78331236e-06
   3.18897533e-06   2.95253229e-06   2.52884279e-06   2.19936673e-06
   1.63559075e-06   1.40828116e-06   1.30534810e-06   1.13650747e-06
   1.03770366e-06   8.55808918e-07   8.40960831e-07   7.28621920e-07
   6.76086075e-07   6.47764800e-07   5.57736862e-07   4.41677622e-07
   4.17045834e-07   4.06350015e-07   3.49534721e-07   2.92166363e-07
   2.79319158e-07   2.63655781e-07   2.52960935e-07   2.37698883e-07
   2.11300471e-07   1.86681616e-07   1.66082811e-07   1.59578082e-07
   1.54735719e-07   1.41793279e-07

In [10]:
import matplotlib as mpl
mpl.use('TkAgg')

In [11]:
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
from elviz_pca import colnames_to_sample_info_array

plot_info = colnames_to_sample_info_array(pca_input)

In [13]:
plot_info.head()

ID   oxy  rep  week  project
0  100_LOW12   Low    4    12  1056214
1  103_HOW12  High    1    12  1056217
2  104_HOW12  High    2    12  1056220
3  105_HOW12  High    3    12  1056223
4  106_HOW12  High    4    12  1056226

In [17]:
# plot one replicate for now. 

plot_columns = plot_info[plot_info['rep'] == 1] 
plot_columns = plot_columns[plot_columns['oxy'] == 'Low'] 
plot_columns.ID

5     109_LOW13
14    121_LOW14
22      13_LOW5
27       1_LOW4
31      25_LOW6
40      37_LOW7
49      49_LOW8
58      61_LOW9
66     73_LOW10
75     85_LOW11
84     97_LOW12
Name: ID, dtype: object

In [30]:
# X_r = pca.fit(X).transform(X)
X_r = pca.fit(pca_input).transform(pca_input)
print(X_r)

[[ -4.48151320e+00  -5.33210663e-01]
 [ -1.58622114e+00   1.02839336e+00]
 [ -6.45682617e-01   5.99480032e-01]
 [ -2.54760434e-01   4.48907200e-01]
 [ -1.67860196e-01   6.54592325e-01]
 [ -1.55939167e-01   1.39056540e-01]
 [ -9.74966345e-02   6.56389481e-02]
 [ -6.42875380e-02   1.55049209e-01]
 [ -4.13732722e-02   1.83117475e-02]
 [ -2.29992469e-02   1.67256718e-02]
 [ -1.74263552e-03  -8.05079220e-03]
 [  8.09796747e-03  -1.15158733e-03]
 [  2.00197689e-02   1.24676800e-02]
 [  2.52894760e-02   2.30382688e-03]
 [  2.25571462e-02  -5.98713266e-03]
 [  2.29722552e-02  -7.01624252e-03]
 [  2.27373112e-02  -1.39645207e-02]
 [  2.88568331e-02  -7.59380116e-03]
 [  3.21594987e-02  -2.20834123e-03]
 [  3.21851633e-02  -5.01116863e-03]
 [  3.30700916e-02  -8.06581298e-03]
 [  3.81367269e-02   3.16338065e-03]
 [  3.21442198e-02  -1.49632930e-02]
 [  3.24012623e-02  -1.49427238e-02]
 [  3.32474106e-02  -1.44449987e-02]
 [  3.54999122e-02  -9.62813627e-03]
 [  3.31862517e-02  -1.71430563e-02]
 

In [29]:
print(pca_input.shape)
print(X_r.shape)

(195, 88)
(195, 2)


In [ ]:
plot_

In [14]:
# COLOR by week, and oxygen.  (weeks = 14, oxygen = 2 --> 28 labels)


plt.figure()
y=plot_info
for c, i, target_name in zip("rgb", [0, 1, 2], target_names):
    plt.scatter(pca[y == i, 0], pca[y == i, 1], c=c, label=target_name)
#for c, i, target_name in zip("rgb", [0, 1, 2], target_names):
#    plt.scatter(pca[y == i, 0], pca[y == i, 1], c=c, label=target_name)
plt.legend()
plt.title('PCA of IRIS dataset')
plt.show()

NameError: name 'target_names' is not defined

# Using Iris Example

http://scikit-learn.org/stable/auto_examples/decomposition/plot_pca_vs_lda.html

In [18]:
from sklearn import datasets

iris = datasets.load_iris()

X = iris.data
print(X)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [24]:
y = iris.target
print(y)
print(y.shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
(150,)


In [25]:
target_names = iris.target_names
print(target_names)

['setosa' 'versicolor' 'virginica']


In [26]:
pca = PCA(n_components=2)
# .fit is _______
# .transform is _____
# This produces _______
X_r = pca.fit(X).transform(X)

In [27]:
print(X_r.shape)

(150, 2)


In [ ]:
X_r

In [ ]:
list(zip("rgb", [0, 1, 2], target_names))

In [ ]:
X_r[y == 2, 0]

In [ ]:
plt.figure()
for c, i, target_name in zip("rgb", [0, 1, 2], target_names):
    # iterating over [('r', 0, 'setosa'), ('g', 1, 'versicolor'), ('b', 2, 'virginica')]
    # X_r[y == i, 0] is 
    plt.scatter(X_r[y == i, 0], X_r[y == i, 1], c=c, label=target_name)
plt.legend()
plt.title('PCA of IRIS dataset')